INSERT INTO member_states (code, name, transitional_months, transitional_end_date, application_deadline, notes) VALUES
  ('AT', 'Austria',       12, '2025-12-30', NULL,         NULL),
  ('BE', 'Belgium',       18, '2026-07-01', NULL,         NULL),
  ('BG', 'Bulgaria',      18, '2026-07-01', '2025-10-08', 'Application deadline 8 Oct 2025'),
  ('CY', 'Cyprus',        18, '2026-07-01', NULL,         NULL),
  ('CZ', 'Czechia',       18, '2026-07-01', '2025-07-31', 'Application deadline 31 Jul 2025'),
  ('DE', 'Germany',       12, '2025-12-31', NULL,         NULL),
  ('DK', 'Denmark',       NULL, NULL,       '2024-12-30', 'No transitional period; application deadline was MiCA day-one (30 Dec 2024)'),
  ('EE', 'Estonia',       18, '2026-07-01', NULL,         NULL),
  ('ES', 'Spain',         18, '2026-07-01', NULL,         NULL),
  ('FI', 'Finland',        6, '2025-06-30', NULL,         NULL),
  ('FR', 'France',        18, '2026-07-01', NULL,         NULL),
  ('GR', 'Greece',        18, '2026-07-01', NULL,         NULL),
  ('HR', 'Croatia',       18, '2026-07-01', NULL,         NULL),
  ('HU', 'Hungary',        6, '2025-06-30', NULL,         NULL),
  ('IE', 'Ireland',       12, '2025-12-31', NULL,         NULL),
  ('IT', 'Italy',         18, '2026-06-30', '2025-12-30', 'Operating end 30 Jun 2026; application filing deadline 30 Dec 2025 (DL 95/2025)'),
  ('LT', 'Lithuania',     12, '2025-12-31', NULL,         NULL),
  ('LU', 'Luxembourg',    18, '2026-07-01', NULL,         NULL),
  ('LV', 'Latvia',         6, '2025-06-30', NULL,         NULL),
  ('MT', 'Malta',         18, '2026-07-01', NULL,         NULL),
  ('NL', 'Netherlands',    6, '2025-06-30', NULL,         NULL),
  ('PL', 'Poland',        18, '2026-07-01', NULL,         'Crypto-Assets Market Act vetoed Dec 2025; defaults to EU-max 18 months'),
  ('PT', 'Portugal',      18, '2026-07-01', NULL,         NULL),
  ('RO', 'Romania',       18, '2026-07-01', NULL,         NULL),
  ('SE', 'Sweden',         9, '2025-09-30', NULL,         NULL),
  ('SI', 'Slovenia',       6, '2025-06-30', NULL,         NULL),
  ('SK', 'Slovakia',      12, '2025-12-31', NULL,         NULL),
  ('NO', 'Norway',        12, '2025-12-31', NULL,         'EEA member'),
  ('IS', 'Iceland',       18, '2026-07-01', NULL,         'EEA member'),
  ('LI', 'Liechtenstein', 18, '2026-07-01', NULL,         'EEA member');

INSERT INTO ncas (state_code, name, abbreviation, register_url) VALUES
  ('DE', 'Federal Financial Supervisory Authority', 'BaFin',  'https://www.bafin.de/EN/Supervision/FinTech/Blockchain/MiCAR/micar_node_en.html'),
  ('NL', 'Netherlands Authority for Financial Markets', 'AFM', 'https://www.afm.nl/en/professionals/onderwerpen/crypto'),
  ('FR', 'Autorité des marchés financiers', 'AMF',             'https://www.amf-france.org/en/professionals/fintech/my-relations-amf/obtain-dasp-authorisation-psan'),
  ('IE', 'Central Bank of Ireland', 'CBI',                    'https://www.centralbank.ie/regulation/industry-market-sectors/crypto-asset-service-providers'),
  ('MT', 'Malta Financial Services Authority', 'MFSA',        'https://www.mfsa.mt/fintech/crypto-assets/'),
  ('CY', 'Cyprus Securities and Exchange Commission', 'CySEC','https://www.cysec.gov.cy/en-GB/regulations/fintech/crypto-assets/'),
  ('LU', 'Commission de Surveillance du Secteur Financier', 'CSSF', 'https://www.cssf.lu/en/crypto-assets/'),
  ('ES', 'Comisión Nacional del Mercado de Valores', 'CNMV',  'https://www.cnmv.es/portal/Consultas/Busqueda.aspx?lang=en'),
  ('IT', 'Bank of Italy / CONSOB', 'BI/CONSOB',               'https://www.bancaditalia.it/compiti/vigilanza/intermediari/operatori-fintech/index.html');
